all:
	/usr/local/go/bin/go build server.go player.go ball.go run_game.go accept_incomming_connections.go find_server_service.go int_slice_conversions.go constants.go
run:
	/usr/local/go/bin/go run server.go player.go ball.go run_game.go accept_incomming_connections.go find_server_service.go int_slice_conversions.go constants.go